services:
  notara:
    build:
      context: .
      dockerfile: Dockerfile
    image: notara
    container_name: notara
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PG_USER=notara
      - PG_PASSWORD=password
      - PG_DATABASE=notara
    volumes:
      - notara_data:/data

volumes:
  notara_data:
